export const SAVE_FORM_REQUEST = "SAVE_FORM_REQUEST";
export const SAVE_FORM_SUCCESS = "SAVE_FORM_SUCCESS";
export const SAVE_FORM_ERROR = "SAVE_FORM_ERROR";

//User Update
export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
//User Delete
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";
